# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b8cdeb76d1d8868d051820aee4953d909c0de7ae199f6eb05329b180b347fd1b836b8c2f9087d59f464d7873e76b09d5f3289444a1d42d4e5a19efac94588cb3

test:
  secret_key_base: f30c4b81151936cd5811d61ca52947d67d14d6e9d173444abb79aa0c1870f6b3a594af3f246f66f3f648dccad883377097d6c3abef6303a1db7a453bb3cdfe41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
